import { theme } from "../operationalShell.jsx";

/** Ciemny motyw dashboard — spójny z operationalShell (theme). */
export const s = {
  page: {
    padding: "clamp(0.75rem, 2vw, 1.75rem) clamp(0.75rem, 3vw, 2rem)",
    width: "100%",
    maxWidth: "100%",
    margin: 0,
    flex: "1 1 auto",
    minHeight: "100vh",
    boxSizing: "border-box",
    fontFamily: 'system-ui, "Segoe UI", Roboto, sans-serif',
    lineHeight: 1.55,
    color: theme.text,
    background: theme.bg,
    textAlign: "left",
  },
  h2: {
    fontSize: "1.2rem",
    marginTop: "2rem",
    marginBottom: "0.75rem",
    fontWeight: 700,
    color: "#ffffff",
    letterSpacing: "-0.02em",
  },
  code: {
    fontSize: "0.88em",
    padding: "0.12rem 0.4rem",
    borderRadius: "4px",
    background: "#242424",
    color: "#d4d4d4",
    border: "1px solid #333",
  },
  form: {
    display: "grid",
    gap: "0.85rem",
    maxWidth: "min(28rem, 100%)",
    padding: "1.25rem 1.35rem",
    border: `1px solid ${theme.border}`,
    borderRadius: "12px",
    background: theme.surface,
    marginBottom: "2rem",
    boxShadow: "0 4px 24px -10px rgba(0,0,0,0.4)",
  },
  /** Rozbite border / tło — żeby nie mieszać shorthand z `borderColor` / `backgroundColor` przy podświetleniach (React 19). */
  input: {
    padding: "0.55rem 0.65rem",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: theme.border,
    borderRadius: "10px",
    font: "inherit",
    boxSizing: "border-box",
    width: "100%",
    backgroundColor: "rgba(11,15,20,0.6)",
    color: theme.text,
    outline: "none",
  },
  label: {
    display: "grid",
    gap: "0.35rem",
    fontSize: "0.82rem",
    color: theme.muted,
    fontWeight: 500,
  },
  btn: {
    padding: "0.6rem 1.15rem",
    borderRadius: "10px",
    border: `1px solid ${theme.action}`,
    background: theme.action,
    color: "#ffffff",
    font: "inherit",
    fontWeight: 600,
    cursor: "pointer",
    boxShadow: "0 4px 14px -4px rgba(249,115,22,0.45)",
    transition: "filter 0.15s ease, transform 0.12s ease",
  },
  btnGhost: {
    padding: "0.5rem 0.95rem",
    borderRadius: "10px",
    border: `1px solid rgba(249,115,22,0.35)`,
    background: "transparent",
    color: theme.text,
    font: "inherit",
    cursor: "pointer",
    transition: "background 0.15s ease, border-color 0.15s ease",
  },
  btnRow: { display: "flex", flexWrap: "wrap", gap: "0.5rem", marginTop: "0.35rem" },
  krBlock: {
    border: `1px solid ${theme.border}`,
    borderRadius: "12px",
    marginBottom: "1rem",
    overflow: "hidden",
    background: theme.surface,
    boxShadow: "0 4px 20px -8px rgba(0,0,0,0.35)",
  },
  krHead: {
    padding: "1rem 1.2rem",
    background: "rgba(17,24,39,0.95)",
    borderBottom: `1px solid ${theme.border}`,
    fontWeight: 600,
    color: "#fff",
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "0.65rem",
  },
  krBody: { padding: "1.1rem" },
  etapItem: {
    padding: "0.55rem 0",
    borderBottom: "1px solid #222",
    color: "#d4d4d4",
  },
  muted: { color: theme.muted, fontSize: "0.92rem" },
  /** Teksty o działach KR — błękit na ciemnym tle */
  dzialInfo: {
    color: "#93c5fd",
    fontSize: "0.92rem",
    lineHeight: 1.5,
  },
  dzialWartosc: { color: "#93c5fd" },
  statusKr: { color: "#a7f3d0", fontSize: "0.9rem" },
  krTopWrap: {
    width: "100%",
    maxWidth: "100%",
    marginBottom: "1.5rem",
    padding: "1.2rem 1.35rem",
    border: `1px solid ${theme.border}`,
    borderRadius: "12px",
    background: theme.surface,
    boxSizing: "border-box",
    boxShadow: "0 4px 24px -10px rgba(0,0,0,0.4)",
  },
  krTopTitle: { margin: "0 0 0.6rem", fontSize: "1.05rem", fontWeight: 600, color: "#fff" },
  krTopList: { margin: 0, paddingLeft: "1.2rem", color: "#d4d4d4" },
  krTopLi: { marginBottom: "0.35rem" },
  errBox: {
    padding: "0.9rem 1.1rem",
    marginBottom: "1rem",
    borderRadius: "10px",
    border: "1px solid #7f1d1d",
    background: "#1c1010",
    color: "#fecaca",
    fontSize: "0.95rem",
  },
  hintBox: {
    padding: "0.9rem 1.1rem",
    marginBottom: "1rem",
    borderRadius: "10px",
    border: "1px solid #854d0e",
    background: "#1c1410",
    fontSize: "0.92rem",
    color: "#fde68a",
  },
  editPanel: {
    marginBottom: "1rem",
    padding: "1rem",
    borderRadius: "10px",
    border: "1px solid #333",
    background: "#121212",
    display: "grid",
    gap: "0.65rem",
  },
  divider: { border: 0, borderTop: "1px solid #252525", margin: "1rem 0" },
  topNav: {
    display: "flex",
    gap: "0.85rem",
    marginTop: "0.35rem",
    marginBottom: "1.15rem",
    flexWrap: "wrap",
    alignItems: "center",
  },
  navGroup: {
    display: "flex",
    flexWrap: "wrap",
    gap: "0.4rem",
    alignItems: "center",
  },
  navSep: {
    width: "1px",
    height: "1.75rem",
    background: "#333",
    alignSelf: "center",
  },
  btnNavAdd: {
    padding: "0.48rem 0.85rem",
    borderRadius: "8px",
    border: "1px solid #5c9cfc",
    background: "transparent",
    color: "#7eb6ff",
    font: "inherit",
    fontWeight: 600,
    fontSize: "0.88rem",
    cursor: "pointer",
  },
  btnNav: {
    padding: "0.55rem 1.35rem",
    borderRadius: "8px",
    border: "1px solid #3f3f3f",
    background: "#141414",
    color: "#a3a3a3",
    font: "inherit",
    fontWeight: 600,
    cursor: "pointer",
  },
  btnNavActive: {
    padding: "0.55rem 1.35rem",
    borderRadius: "8px",
    border: "1px solid #e5e5e5",
    background: "#f5f5f5",
    color: "#0a0a0a",
    font: "inherit",
    fontWeight: 600,
    cursor: "pointer",
  },
  tableWrap: {
    overflowX: "auto",
    width: "100%",
    maxWidth: "100%",
    border: `1px solid ${theme.border}`,
    borderRadius: "12px",
    background: theme.surface,
    marginBottom: "1.5rem",
    boxSizing: "border-box",
    WebkitOverflowScrolling: "touch",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: "0.9rem",
    color: "#e5e5e5",
  },
  th: {
    textAlign: "left",
    padding: "0.65rem 0.75rem",
    borderBottom: "1px solid #2a2a2a",
    background: "#141414",
    color: "#fff",
    fontWeight: 600,
    whiteSpace: "nowrap",
  },
  td: {
    textAlign: "left",
    padding: "0.55rem 0.75rem",
    borderBottom: "1px solid #222",
    verticalAlign: "top",
  },
  thBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.28rem",
    margin: 0,
    padding: 0,
    border: "none",
    background: "transparent",
    color: "inherit",
    font: "inherit",
    fontWeight: 600,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  /** Tabela etapów (`public.etapy`) — mniejsza czcionka, więcej kolumn na ekranie. */
  kmTable: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: "0.7rem",
    lineHeight: 1.35,
    color: "#ddd",
    tableLayout: "fixed",
  },
  kmTh: {
    textAlign: "left",
    padding: "0.35rem 0.4rem",
    borderBottom: "1px solid #2a2a2a",
    background: "#141414",
    color: "#f0f0f0",
    fontWeight: 600,
    fontSize: "0.68rem",
    verticalAlign: "bottom",
    wordBreak: "break-word",
  },
  kmTd: {
    textAlign: "left",
    padding: "0.32rem 0.4rem",
    borderBottom: "1px solid #222",
    verticalAlign: "top",
    fontSize: "0.7rem",
    wordBreak: "break-word",
    overflowWrap: "break-word",
  },
  kmTdAkcje: {
    textAlign: "right",
    whiteSpace: "nowrap",
    width: "4.5rem",
  },
  /** Oś czasu — karty operacyjne (pulpit). */
  pulpitLiNowy: {
    display: "flex",
    alignItems: "flex-start",
    gap: "0.5rem",
    minWidth: 0,
    padding: "0.5rem 0",
    paddingLeft: "0.15rem",
    marginLeft: 0,
    borderBottom: "1px solid rgba(148,163,184,0.08)",
    listStyle: "none",
    borderRadius: "12px",
  },
  pulpitLiUwaga: {
    paddingLeft: "0.5rem",
    marginLeft: "-0.1rem",
    borderLeft: "3px solid #f87171",
    background: "rgba(248,113,113,0.06)",
  },
  pulpitDataCol: {
    flex: "0 0 5rem",
    color: "#94a3b8",
    fontVariantNumeric: "tabular-nums",
    whiteSpace: "nowrap",
    fontSize: "0.72rem",
    lineHeight: 1.35,
    paddingTop: "0.15rem",
  },
  pulpitDataColUwaga: { color: "#fca5a5", fontWeight: 600 },
  pulpitKartaTekst: {
    flex: "1 1 auto",
    minWidth: 0,
    fontSize: "0.78rem",
    lineHeight: 1.4,
    color: "#e2e8f0",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    paddingTop: "0.1rem",
  },
  pulpitKartaTekstUwaga: { color: "#fecaca", fontWeight: 600 },
  pulpitTerazLinia: {
    flex: "1 1 auto",
    height: "2px",
    background: "linear-gradient(90deg, transparent, #4ade80 10%, #4ade80 90%, transparent)",
    minWidth: "1rem",
  },
};
