import { theme } from "../operationalShell.jsx";

/** Jasny motyw dashboard — spójny z operationalShell (theme). */
export const s = {
  page: {
    padding: "clamp(0.75rem, 2vw, 1.75rem) clamp(0.75rem, 3vw, 2rem)",
    width: "100%",
    maxWidth: "100%",
    margin: 0,
    flex: "1 1 auto",
    minHeight: "100vh",
    boxSizing: "border-box",
    fontFamily: 'system-ui, "Segoe UI", Roboto, sans-serif',
    lineHeight: 1.55,
    color: theme.text,
    background: theme.bg,
    textAlign: "left",
  },
  h2: {
    fontSize: "1.2rem",
    marginTop: "2rem",
    marginBottom: "0.75rem",
    fontWeight: 700,
    color: theme.text,
    letterSpacing: "-0.02em",
  },
  code: {
    fontSize: "0.88em",
    padding: "0.12rem 0.4rem",
    borderRadius: "4px",
    background: "#e2e8f0",
    color: "#0f172a",
    border: "1px solid #cbd5e1",
  },
  form: {
    display: "grid",
    gap: "0.85rem",
    maxWidth: "min(28rem, 100%)",
    padding: "1.25rem 1.35rem",
    border: `1px solid ${theme.border}`,
    borderRadius: "12px",
    background: theme.surface,
    marginBottom: "2rem",
    boxShadow: "0 4px 18px -12px rgba(15,23,42,0.18)",
  },
  /** Rozbite border / tło — żeby nie mieszać shorthand z `borderColor` / `backgroundColor` przy podświetleniach (React 19). */
  input: {
    padding: "0.55rem 0.65rem",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: theme.border,
    borderRadius: "10px",
    font: "inherit",
    boxSizing: "border-box",
    width: "100%",
    backgroundColor: "#ffffff",
    color: theme.text,
    outline: "none",
  },
  label: {
    display: "grid",
    gap: "0.35rem",
    fontSize: "0.82rem",
    color: theme.muted,
    fontWeight: 500,
  },
  btn: {
    padding: "0.6rem 1.15rem",
    borderRadius: "10px",
    border: `1px solid ${theme.action}`,
    background: theme.action,
    color: "#ffffff",
    font: "inherit",
    fontWeight: 600,
    cursor: "pointer",
    boxShadow: "0 4px 14px -4px rgba(234,88,12,0.35)",
    transition: "filter 0.15s ease, transform 0.12s ease",
  },
  btnGhost: {
    padding: "0.5rem 0.95rem",
    borderRadius: "10px",
    border: `1px solid rgba(234,88,12,0.4)`,
    background: "#ffffff",
    color: theme.text,
    font: "inherit",
    cursor: "pointer",
    transition: "background 0.15s ease, border-color 0.15s ease",
  },
  btnRow: { display: "flex", flexWrap: "wrap", gap: "0.5rem", marginTop: "0.35rem" },
  krBlock: {
    border: `1px solid ${theme.border}`,
    borderRadius: "12px",
    marginBottom: "1rem",
    overflow: "hidden",
    background: theme.surface,
    boxShadow: "0 4px 16px -10px rgba(15,23,42,0.14)",
  },
  krHead: {
    padding: "1rem 1.2rem",
    background: "#f8fafc",
    borderBottom: `1px solid ${theme.border}`,
    fontWeight: 600,
    color: theme.text,
    display: "flex",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "0.65rem",
  },
  krBody: { padding: "1.1rem" },
  etapItem: {
    padding: "0.55rem 0",
    borderBottom: "1px solid #e2e8f0",
    color: theme.text,
  },
  muted: { color: theme.muted, fontSize: "0.92rem" },
  /** Teksty o działach KR — błękit na jasnym tle */
  dzialInfo: {
    color: "#0369a1",
    fontSize: "0.92rem",
    lineHeight: 1.5,
  },
  dzialWartosc: { color: "#0369a1" },
  statusKr: { color: "#166534", fontSize: "0.9rem" },
  krTopWrap: {
    width: "100%",
    maxWidth: "100%",
    marginBottom: "1.5rem",
    padding: "1.2rem 1.35rem",
    border: `1px solid ${theme.border}`,
    borderRadius: "12px",
    background: theme.surface,
    boxSizing: "border-box",
    boxShadow: "0 4px 18px -12px rgba(15,23,42,0.16)",
  },
  krTopTitle: { margin: "0 0 0.6rem", fontSize: "1.05rem", fontWeight: 600, color: theme.text },
  krTopList: { margin: 0, paddingLeft: "1.2rem", color: theme.text },
  krTopLi: { marginBottom: "0.35rem" },
  errBox: {
    padding: "0.9rem 1.1rem",
    marginBottom: "1rem",
    borderRadius: "10px",
    border: "1px solid #fecaca",
    background: "#fef2f2",
    color: "#991b1b",
    fontSize: "0.95rem",
  },
  hintBox: {
    padding: "0.9rem 1.1rem",
    marginBottom: "1rem",
    borderRadius: "10px",
    border: "1px solid #fde68a",
    background: "#fffbeb",
    fontSize: "0.92rem",
    color: "#92400e",
  },
  editPanel: {
    marginBottom: "1rem",
    padding: "1rem",
    borderRadius: "10px",
    border: `1px solid ${theme.border}`,
    background: "#f8fafc",
    display: "grid",
    gap: "0.65rem",
  },
  divider: { border: 0, borderTop: "1px solid #e2e8f0", margin: "1rem 0" },
  topNav: {
    display: "flex",
    gap: "0.85rem",
    marginTop: "0.35rem",
    marginBottom: "1.15rem",
    flexWrap: "wrap",
    alignItems: "center",
  },
  navGroup: {
    display: "flex",
    flexWrap: "wrap",
    gap: "0.4rem",
    alignItems: "center",
  },
  navSep: {
    width: "1px",
    height: "1.75rem",
    background: "#cbd5e1",
    alignSelf: "center",
  },
  btnNavAdd: {
    padding: "0.48rem 0.85rem",
    borderRadius: "8px",
    border: "1px solid #0284c7",
    background: "#ffffff",
    color: "#0369a1",
    font: "inherit",
    fontWeight: 600,
    fontSize: "0.88rem",
    cursor: "pointer",
  },
  btnNav: {
    padding: "0.55rem 1.35rem",
    borderRadius: "8px",
    border: `1px solid ${theme.border}`,
    background: "#ffffff",
    color: theme.muted,
    font: "inherit",
    fontWeight: 600,
    cursor: "pointer",
  },
  btnNavActive: {
    padding: "0.55rem 1.35rem",
    borderRadius: "8px",
    border: "1px solid #0f172a",
    background: "#0f172a",
    color: "#ffffff",
    font: "inherit",
    fontWeight: 600,
    cursor: "pointer",
  },
  tableWrap: {
    overflowX: "auto",
    width: "100%",
    maxWidth: "100%",
    border: `1px solid ${theme.border}`,
    borderRadius: "12px",
    background: theme.surface,
    marginBottom: "1.5rem",
    boxSizing: "border-box",
    WebkitOverflowScrolling: "touch",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: "0.9rem",
    color: theme.text,
  },
  th: {
    textAlign: "left",
    padding: "0.65rem 0.75rem",
    borderBottom: "1px solid #e2e8f0",
    background: "#e2e8f0",
    color: theme.text,
    fontWeight: 600,
    whiteSpace: "nowrap",
  },
  td: {
    textAlign: "left",
    padding: "0.55rem 0.75rem",
    borderBottom: "1px solid #e2e8f0",
    verticalAlign: "top",
  },
  thBtn: {
    display: "inline-flex",
    alignItems: "center",
    gap: "0.28rem",
    margin: 0,
    padding: 0,
    border: "none",
    background: "transparent",
    color: "inherit",
    font: "inherit",
    fontWeight: 600,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  /** Tabela etapów (`public.etapy`) — mniejsza czcionka, więcej kolumn na ekranie. */
  kmTable: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: "0.7rem",
    lineHeight: 1.35,
    color: theme.text,
    tableLayout: "fixed",
  },
  kmTh: {
    textAlign: "left",
    padding: "0.35rem 0.4rem",
    borderBottom: "1px solid #e2e8f0",
    background: "#e2e8f0",
    color: theme.text,
    fontWeight: 600,
    fontSize: "0.68rem",
    verticalAlign: "bottom",
    wordBreak: "break-word",
  },
  kmTd: {
    textAlign: "left",
    padding: "0.32rem 0.4rem",
    borderBottom: "1px solid #e2e8f0",
    verticalAlign: "top",
    fontSize: "0.7rem",
    wordBreak: "break-word",
    overflowWrap: "break-word",
  },
  kmTdAkcje: {
    textAlign: "right",
    whiteSpace: "nowrap",
    width: "4.5rem",
  },
  /** Oś czasu — karty operacyjne (pulpit). */
  pulpitLiNowy: {
    display: "flex",
    alignItems: "flex-start",
    gap: "0.5rem",
    minWidth: 0,
    padding: "0.5rem 0",
    paddingLeft: "0.15rem",
    marginLeft: 0,
    borderBottom: "1px solid rgba(100,116,139,0.18)",
    listStyle: "none",
    borderRadius: "12px",
  },
  pulpitLiUwaga: {
    paddingLeft: "0.5rem",
    marginLeft: "-0.1rem",
    borderLeft: "3px solid #dc2626",
    background: "rgba(220,38,38,0.06)",
  },
  pulpitDataCol: {
    flex: "0 0 5rem",
    color: "#64748b",
    fontVariantNumeric: "tabular-nums",
    whiteSpace: "nowrap",
    fontSize: "0.72rem",
    lineHeight: 1.35,
    paddingTop: "0.15rem",
  },
  pulpitDataColUwaga: { color: "#b91c1c", fontWeight: 600 },
  pulpitKartaTekst: {
    flex: "1 1 auto",
    minWidth: 0,
    fontSize: "0.78rem",
    lineHeight: 1.4,
    color: theme.text,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    paddingTop: "0.1rem",
  },
  pulpitKartaTekstUwaga: { color: "#991b1b", fontWeight: 600 },
  pulpitTerazLinia: {
    flex: "1 1 auto",
    height: "2px",
    background: "linear-gradient(90deg, transparent, #16a34a 10%, #16a34a 90%, transparent)",
    minWidth: "1rem",
  },
};
