-- Auto-generated from XLSX: import_pracownik_from_xlsx.py
-- Columns limited to existing app fields: nr, imie_nazwisko, telefon, email, is_active
BEGIN;

CREATE TEMP TABLE tmp_pracownik_import (
  nr text,
  imie_nazwisko text,
  telefon text,
  email text,
  is_active boolean
) ON COMMIT DROP;

INSERT INTO tmp_pracownik_import (nr, imie_nazwisko, telefon, email, is_active)
VALUES
  ('001', 'Monika Jakubowska', NULL, NULL, true),
  ('002', 'Marcin Ciszek', '48791739309', 'mciszek86@gmail.com', true),
  ('003', 'Małgorzata Franczak', '48792413114', 'malgorzata.franczak@g4geodezja.pl', true),
  ('004', 'Małgorzata Flis', '48790899307', 'malgorzata.flis@g4geodezja.pl', true),
  ('005', 'Anna Iskierka', '48796872400', 'anna.iskierka@g4geodezja.pl', true),
  ('006', 'Anna Górecka-Drabik', NULL, NULL, true),
  ('007', 'Iwona Gregonis', NULL, NULL, true),
  ('008', 'Marcin Gruba', NULL, NULL, true),
  ('009', 'Anna Swatowska', '48576282825', 'anna.swatowska@g4geodezja.pl', true),
  ('010', 'Michał Haller de Hallenburg', NULL, NULL, true),
  ('011', 'Anna Homik', '48796872304', 'anna.homik@g4geodezja.pl', true),
  ('012', 'Jarosław Jagoda', NULL, NULL, true),
  ('013', 'Barbara Kłapeć', NULL, NULL, true),
  ('014', 'Sebastian Buk', NULL, NULL, true),
  ('015', 'Paweł Kiełkowicz', NULL, NULL, true),
  ('016', 'Łukasz Kobierski', NULL, NULL, true),
  ('017', 'Łukasz Kołpak', NULL, NULL, true),
  ('018', 'Kamil Kozieł', NULL, NULL, true),
  ('019', 'Bogumił Kuciński', '48796872302', 'bogumil.kucinski@g4geodezja.pl', true),
  ('020', 'Maciej Sumara', NULL, NULL, true),
  ('021', 'Wojciech Kralka', NULL, NULL, true),
  ('022', 'Marcin Łanecki', '48790899306', 'marcin.lanecki@g4geodezja.pl', true),
  ('023', 'Damian Markiewicz', '48796872305', 'damian.markiewicz@g4geodezja.pl', true),
  ('024', 'Grzegorz Polkowski', NULL, NULL, true),
  ('025', 'Daniel Janik', NULL, NULL, true),
  ('026', 'Marcin Radoń', NULL, NULL, true),
  ('027', 'Fabian Świgut', NULL, NULL, true),
  ('028', 'Joanna Kardasz', NULL, NULL, true),
  ('029', 'Dorota Wojtan', NULL, NULL, true),
  ('030', 'Andrzej Jakubowski', NULL, NULL, true),
  ('031', 'Iwona Kisała', NULL, NULL, true),
  ('032', 'Paulina Jędrzejczak', NULL, NULL, true),
  ('033', 'Kinga Ciszek', '603 237 606', 'kinga.ciszek@g4geodezja.pl', true),
  ('034', 'Norbert Borsukiewicz', NULL, NULL, true),
  ('035', 'Kamil Kot', '48791839308', 'kamil.kot@g4geodezja.pl', true),
  ('036', 'Artur Walens', NULL, NULL, true),
  ('037', 'Joanna Warzecha', NULL, NULL, true),
  ('038', 'Marcin Rojek', '48531303800', 'marcin.rojek@g4geodezja.pl', true),
  ('039', 'Magdalena Trojanowska', '48578200701', 'magdalena.trojanowska@g4geodezja.pl', true),
  ('040', 'Magda Słodka', '728 913 418', 'magda.slodka@g4geodezja.pl', true),
  ('041', 'Aleksandra Klima', '48793294992', 'aleksandra.kusmierczyk@g4geodezja.pl', true),
  ('042', 'Adrian Skuza', '667 061 214', 'adrian.skuza@g4geodezja.pl', true),
  ('043', 'Mateusz Pikulik', NULL, NULL, true),
  ('044', 'Sylwia Boroń', NULL, NULL, true),
  ('045', 'Katarzyna Rzadek', NULL, NULL, true),
  ('046', 'Anna Basiaga', NULL, NULL, true),
  ('047', 'Katarzyna Staromłyńska', NULL, NULL, true),
  ('048', 'Piotr Garsztka', '48796872303', 'piotr.garsztka@g4geodezja.pl', true),
  ('049', 'Marcin Skorupa', NULL, NULL, true),
  ('050', 'Maciej Bednarczyk', '48796872500', 'maciej.bednarczyk@g4geodezja.pl', true),
  ('051', 'Agnieszka Gońka', NULL, NULL, true),
  ('052', 'Oliwia Kiecana', '604 628 345', 'oliwia.kiecana@g4geodezja.pl', true),
  ('053', 'Mateusz Jawor', '604 607 318', 'mateusz.jawor@g4geodezja.pl', true),
  ('054', 'Roksana Stryjak', '661 444 507', 'dzial.handlowy@g4geodezja.pl', true),
  ('055', 'Miłosz Passoń', NULL, NULL, true),
  ('056', 'Michala Sacher', NULL, NULL, true),
  ('057', 'Piotr Bigaj', NULL, NULL, true),
  ('058', 'Łukasz Grądzki', NULL, NULL, true),
  ('059', 'Andrzej Pyrz', NULL, NULL, true),
  ('060', 'Arkadiusz Szczepanik', NULL, NULL, true),
  ('061', 'Paweł Zgraja', NULL, NULL, true),
  ('062', 'Maciej Bajorek', NULL, NULL, true),
  ('063', 'Rafał Skowronek', NULL, NULL, true),
  ('064', 'Hubert Węglarski', NULL, NULL, true),
  ('065', 'Ireneusz Faryna', NULL, NULL, true),
  ('066', 'Wojciech Lorenc', NULL, NULL, true),
  ('067', 'Sebastian Bąk', NULL, NULL, true),
  ('068', 'Andrzej Chmielowski', NULL, NULL, true),
  ('069', 'Karolina Bieleń', NULL, NULL, true),
  ('070', 'Agnieszka Brachman', NULL, NULL, true),
  ('071', 'Kamil Kieca', NULL, NULL, true),
  ('072', 'Krzysztof Wieliński', NULL, NULL, true),
  ('073', 'Krzysztof Wieliński', NULL, NULL, true),
  ('074', 'Rafał Psonak', NULL, NULL, true),
  ('075', 'Anna Rak', NULL, NULL, true),
  ('076', 'Jacek Dorobek', NULL, NULL, true),
  ('077', 'Marcin Gędłek', NULL, NULL, true),
  ('078', 'Danuta Szydełko', NULL, 'lszydelko@o2.pl', true),
  ('079', 'Wojciech Kołtyś', NULL, NULL, true),
  ('080', 'Karol Ryfczyński', NULL, NULL, true),
  ('081', 'Marcin Stachowicz', NULL, NULL, true),
  ('082', 'Emil Kotulski', NULL, NULL, true),
  ('083', 'Marcin Szpak', NULL, NULL, true),
  ('084', 'Marcin Paskuda', NULL, NULL, true),
  ('085', 'Adrkadiusz Gucwa', NULL, NULL, true),
  ('086', 'Anna Żelazna', NULL, NULL, true),
  ('087', 'Artur Buszek', NULL, NULL, true),
  ('088', 'Katarzyna Płużek', NULL, NULL, true),
  ('089', 'Dominik Główczyk', NULL, NULL, true),
  ('090', 'Agata Sobielga', NULL, NULL, true),
  ('091', 'Michał Kuśmierczyk', NULL, NULL, true),
  ('092', 'Karolina Żurek', NULL, NULL, true),
  ('093', 'Jakub Śledź', NULL, NULL, true),
  ('094', 'Michał Niemczyk', NULL, NULL, true),
  ('095', 'Marek Maślach', NULL, NULL, true),
  ('096', 'Domika Kruk', NULL, NULL, true),
  ('097', 'Paweł Gaj', NULL, NULL, true),
  ('098', 'Krystian Buratowski', NULL, NULL, true),
  ('099', 'Sławomir Polański', NULL, NULL, true),
  ('100', 'Mateusz Węgrzynkiewicz', NULL, NULL, true),
  ('101', 'Magdalena Kałuża', NULL, NULL, true),
  ('102', 'Michał Kuder', NULL, NULL, true),
  ('103', 'Grzegorz Przytocki', NULL, NULL, true),
  ('104', 'Jakub Smoleń', NULL, NULL, true),
  ('105', 'Piotr Tentszert', NULL, NULL, true),
  ('106', 'Kacper Werenkowicz', NULL, NULL, true),
  ('107', 'Jakub Wiśniewski', NULL, NULL, true),
  ('108', 'Mateusz Zieliński', NULL, NULL, true),
  ('109', 'Monika Urban', NULL, NULL, true),
  ('110', 'Magdalena Tendera', NULL, NULL, true),
  ('111', 'Jan Drabik', NULL, 'anna.gorecka.drabik@gmail.com', true),
  ('112', 'Urszula Piórczyk', NULL, NULL, true),
  ('113', 'Michał Mokrzyński', NULL, NULL, true),
  ('114', 'Przemysław Szlęzak', '881 685 521', 'przemyslaw.szlezak@g4geodezja.pl', true),
  ('115', 'Urszula Miśkiewicz', NULL, NULL, true),
  ('116', 'Paweł Tetke', NULL, NULL, true),
  ('118', 'Paweł Szalak', '665522005', 'p.szalak94@gmail.com', true),
  ('119', 'Klaudia Stasiaczek', NULL, NULL, true),
  ('120', 'Tomasz Wachowski', NULL, NULL, true),
  ('121', 'Sebastian Soja', NULL, NULL, true),
  ('122', 'Karol Szczuchniak', NULL, NULL, true),
  ('123', 'Monika Szcząchor', NULL, NULL, true),
  ('124', 'Krzysztof Matoszko', NULL, NULL, true),
  ('125', 'Bartłomiej Głąb', NULL, NULL, true),
  ('126', 'Aleksandra Bryła', NULL, NULL, true),
  ('127', 'Marta Płatek', NULL, NULL, true),
  ('128', 'Monika Burdek', NULL, NULL, true),
  ('129', 'Artur Zych', NULL, NULL, true),
  ('130', 'Magdalena Lasek', NULL, 'madlen.lasek@gmail.com', true),
  ('131', 'Michał Moskała', NULL, NULL, true),
  ('132', 'Paweł Gmyz', NULL, NULL, true),
  ('133', 'Mateusz Broszkiewicz', NULL, NULL, true),
  ('134', 'Joanna Stachowicz', NULL, NULL, true),
  ('135', 'Magdalena Bociek', NULL, NULL, true),
  ('136', 'Marcin Zięba', NULL, NULL, true),
  ('137', 'Emilian Piątek', NULL, NULL, true),
  ('138', 'Patryk Pajkert', NULL, NULL, true),
  ('139', 'Norbert Waleński', NULL, NULL, true),
  ('140', 'Agnieszka Jurczak', NULL, NULL, true),
  ('141', 'Maria Gawrysz', NULL, NULL, true),
  ('142', 'Mariola Cader', NULL, NULL, true),
  ('143', 'Iwona Adamczyk', NULL, NULL, true),
  ('144', 'Filip Kucybała', NULL, NULL, true),
  ('145', 'Katarzyna Wawrzynek', '500 858 744', 'katarzyna.wawrzynek@g4geodezja.pl', true),
  ('146', 'Grzegorz Domański', NULL, NULL, true),
  ('147', 'Piotr Czerski', NULL, NULL, true),
  ('148', 'Michał Hałys', NULL, NULL, true),
  ('149', 'Monika Mirus', NULL, NULL, true),
  ('150', 'Paweł Wojtas', NULL, NULL, true),
  ('151', 'Aleksander Trzeciak', NULL, NULL, true),
  ('152', 'Karol Pawłowski', NULL, NULL, true),
  ('153', 'Piotr Jaskółka', NULL, NULL, true),
  ('154', 'Joanna Wasylewicz', NULL, NULL, true),
  ('155', 'Martyna Rerek', NULL, NULL, true),
  ('156', 'Dagmara Wnęk', '48578200308', 'dagmara.debosz@g4geodezja.pl', true),
  ('157', 'Paweł Twardawa', NULL, NULL, true),
  ('158', 'Agata Tolasz', NULL, NULL, true),
  ('159', 'Agnieszka Wojtarek', NULL, NULL, true),
  ('160', 'Justyna Bielak', NULL, NULL, true),
  ('162', 'Tomasz Smyczek', NULL, NULL, true),
  ('163', 'Magdalena Kotarska', NULL, NULL, true),
  ('164', 'Zbigniew Polonis', NULL, NULL, true),
  ('165', 'Dawid Kadłubowski', NULL, NULL, true),
  ('166', 'Renata Pikor', NULL, NULL, true),
  ('167', 'Norbert Rakowiecki', NULL, NULL, true),
  ('168', 'Adam Kostuj', NULL, NULL, true),
  ('169', 'Madalena Jawor', NULL, NULL, true),
  ('170', 'Joanna Gola', NULL, NULL, true),
  ('171', 'Mateusz Żurawiecki', NULL, NULL, true),
  ('172', 'Marcin Hojka', NULL, NULL, true),
  ('173', 'Karol Smardz', NULL, 'obiektowanie@gmail.com', true),
  ('174', 'Katarzyna Litwa', NULL, NULL, true),
  ('175', 'Celina Lorenc', NULL, NULL, true),
  ('176', 'Sebastian Zając', '48578600504', 'sebastian.zajac@g4geodezja.pl', true),
  ('177', 'Joanna Adamska', '48576454540', 'joanna.adamska@g4geodezja.pl', true),
  ('178', 'Krzesimir Blautt', NULL, NULL, true),
  ('179', 'Adrian Kostuch', NULL, NULL, true),
  ('180', 'Michał Straszak', NULL, 'michal.straszak@cahelio.pl', true),
  ('181', 'Adam Kubicki', NULL, NULL, true),
  ('182', 'Anna Izdebska', NULL, NULL, true),
  ('183', 'Vladyslav Chornyi', NULL, 'tcherniyvlad1@gmail.com', true),
  ('184', 'Maurycy Słowiński', NULL, NULL, true),
  ('185', 'Barbara Tyszko', NULL, NULL, true),
  ('186', 'Magdalena Skarbek-Izworska', '48790575737', 'magdalena.skarbek@g4geodezja.pl', true),
  ('187', 'Karolina Ziętek', '519 719 709', 'karolina.zietek@g4geodezja.pl', true),
  ('188', 'Maria Zegar', NULL, 'mzegar97@gmail.com', true),
  ('189', 'Piotr Nicpoń', NULL, 'mzegar97@gmail.com', true),
  ('190', 'Agnieszka Głaz', NULL, NULL, true),
  ('191', 'Paula Piłat', NULL, 'paneckapaula@o2.pl', true),
  ('192', 'Martyna Ściupider', '48578141510', 'martyna.was@g4geodezja.pl', true),
  ('193', 'Angeilika Sielawa', NULL, NULL, true),
  ('194', 'Magdalena Markiewicz', NULL, 'mpuda@go2.pl', true),
  ('195', 'Paweł Waleczek', NULL, 'dmarkiewicz@go2.pl', true),
  ('196', 'Agnieszka Pyrko-Maj', NULL, 'agap83@o2.pl', true),
  ('197', 'Patrycja Synowiec', NULL, 'patrycjasynowiec2@gmail.com', true),
  ('198', 'Karolina Cebulska', NULL, '793284497', true),
  ('199', 'Justyna Ryniak', '48570373434', 'justyna.ryniak@g4geodezja.pl', true),
  ('200', 'Katarzyna Badura', '538 494 736', 'katarzyna.nowak@g4geodezja.pl', true),
  ('201', 'Marcin Rodzeń', NULL, NULL, true),
  ('202', 'Sebastian Pawlik', NULL, NULL, true),
  ('203', 'Agnieszka Sawer', NULL, NULL, true),
  ('204', 'Piotr Rozenbajgier', NULL, NULL, true),
  ('205', 'Michał Kok', NULL, 'pukkix17@gmail.com', true),
  ('206', 'Joanna Bochaczyk', '48578200501', 'joanna.bochaczyk@g4geodezja.pl', true),
  ('207', 'Hanna Flis', NULL, NULL, true),
  ('208', 'Dominika Szczepanik', NULL, NULL, true),
  ('209', 'Dariusz Gala', NULL, NULL, true),
  ('210', 'Aleksander Traczyk', NULL, NULL, true),
  ('211', 'Piotr Szafrański', '48790373787', 'piotr.szafranski@g4geodezja.pl', true),
  ('212', 'Jakub Kocur', NULL, NULL, true),
  ('213', 'Maria Kominek', NULL, NULL, true),
  ('214', 'Michał Rutkowski', NULL, NULL, true),
  ('215', 'Marcin Sławiński', NULL, NULL, true),
  ('216', 'Agnieszka Studniarz', '697 606 391', 'agnieszka.studniarz@g4geodezja.pl', true),
  ('217', 'Elżbieta Włoch', NULL, NULL, true),
  ('218', 'Katarzyna Bugaj', NULL, 'katarzynabugaj98@gmail.com', true),
  ('219', 'Maciej Wierzbicki', '+48 509 153 768', 'wierzbickim90@gmail.com', true),
  ('220', 'Marlena Chruściel', '669 682 851', 'marlena.maron@g4geodezja.pl', true),
  ('221', 'Justyna Kuśnierz', '510055679', 'justyna.kusnierz@g4geodezja.pl', true),
  ('222', 'Joanna Szymczakiewicz', '732 012 355', 'joanna.strzalka@g4geodezja.pl', true),
  ('223', 'Eryk Cholewa', '573 162 597', 'eryk.cholewa@g4geodezja.pl', true),
  ('224', 'Dominika Nowicka', '884 010 881', 'dominika.nowicka@g4geodezja.pl', true),
  ('225', 'Anna Pyzik', '781 533 937', 'anna.pyzik@g4geodezja.pl', true),
  ('226', 'Tomasz Socała', '514 655 764', 'tomasz.socala@g4geodezja.pl', true),
  ('227', 'Dagmara Skwara', '727 421 609', 'dagmara.skwara@g4geodezja.pl', true),
  ('228', 'Tomasz Bielak', NULL, 'tomasz.bielak87@gmail.com', true),
  ('229', 'Alicja Drelich-Prokuska', NULL, 'alicjadrelich@gmail.com', true),
  ('230', 'Artur Branicki', NULL, NULL, true),
  ('231', 'Sławomir Pyzik', '48578171810', 'slawomir.pyzik@g4geodezja.pl', true),
  ('232', 'Jakub Karliński', NULL, 'obiektowanie@gmail.com', true),
  ('233', 'Łukasz Lipiec', NULL, 'obiektowanie@gmail.com', true),
  ('234', 'Marta Bukowska', NULL, 'bukowska.marta12@gmail.com', true),
  ('235', 'Piotr Rozenbajgier', '534108300', 'piotr', true),
  ('236', 'Mariusz Furgała', '601-161-678', 'mariusz.furgala@g4geodezja.pl', true),
  ('237', 'Karol Cieślik', '690 820 809', 'k.cieslik@onet.pl', true),
  ('238', 'Karolina Staroń', '502-705-637', 'karolina.staron@g4geodezja.pl', true),
  ('239', 'Dominik Niejadlik', NULL, 'dominik.niejadlik@g4geodezja.pl', true),
  ('240', 'Joanna Kuś', NULL, NULL, true),
  ('241', 'Maja Jakubowska', NULL, 'maja.jakubowska@o2.pl', true),
  ('242', 'Marcin Puda', NULL, 'marcinpuda@gmail.com', true),
  ('243', 'Mariusz Jastrowicz', NULL, 'mariuzs.jastrowicz@gmail.com', true),
  ('244', 'Sebastian Kostyra', NULL, 'sebastian.kos@gmail.com', true),
  ('245', 'Aleksandra Józefowicz-Stasiak', '723 590 256', 'geodezja.alegeo@gmail.com', true),
  ('246', 'Krzysztof Kiszka', '504 798 955', 'krzysztof.kiszka@g4geodezja.pl', true),
  ('247', 'Ryszard Maleta', NULL, NULL, true),
  ('248', 'Karol Taborski', NULL, 'karoltaborski@gmail.com', true),
  ('249', 'Sławomir Handzlik', NULL, 'shandzlik@gmail.com', true),
  ('250', 'Danuta Małecka', NULL, 'danuta.m14@gmail.com', true),
  ('251', 'Paulina Karaczyn', '504 190 877', 'paulina.ciećkiewicz@g4geodezja.pl', true),
  ('252', 'Mariusz Wroniecki', NULL, 'mariusz.wroniecki@gmail.com', true),
  ('253', 'Dawid Włodarz', '534 693 333', 'dawid.wlodarz@g4geodezja.pl', true),
  ('254', 'Marcin Rybicki', '518 692 101', 'marcin.rybicki@g4geodezja.pl', true),
  ('255', 'Bartłomiej Rój', '515 460 862', 'bartolomiej.roj@g4geodezja.pl', true),
  ('256', 'Paulina Relińska', NULL, 'paulinarel99@gmail.com', true),
  ('257', 'Dawid Szecówka', '668 052 972', 'dawid.szecowka@g4geodezja.pl', true),
  ('258', 'Joanna Bernady', '669972060', 'joanna.bernady@g4geodezja.pl', true),
  ('259', 'Adam Bartecki', NULL, NULL, true),
  ('260', 'Jadwiga Dziadosz', NULL, 'jdstrz@wp.pl', true),
  ('261', 'Karolina Pietrucha', NULL, 'karolina.pietrucha1@gmail.com', true),
  ('262', 'Paweł Wójcik', NULL, 'p.wojcik92@gmail.com', true),
  ('263', 'Zofia Karlińska', NULL, 'zosia8752@wp.pl', true),
  ('264', 'Urszula Kasztulska', '609 986 615', 'urszula.kasztulska@g4geodezja.pl', true),
  ('265', 'Angelika Ożga', '607 793 559', 'angelika.ozga@g4geodezja.pl', true),
  ('266', 'Dariusz Chrzanowski', NULL, 'dariuszchrzanowski@interia.pl', true),
  ('267', 'Paweł Puchalik', NULL, 'pawelpuchalik@gmail.com', true),
  ('268', 'Magdalena Chrzanowska', '662243178', 'magdalena.chrzanowska@g4geodezja.pl', true),
  ('269', 'Wioletta Szafrańska', NULL, 'wiola.szafranska@gmail.com', true),
  ('270', 'Zofia Leśkiewicz', '728996773', 'zofia.leskiewicz@g4geodedezja.pl', true),
  ('271', 'Joanna Drozd', NULL, 'asieczek@o2.pl', true),
  ('272', 'Paulina Ryzner', '793408277', 'paulina.ryzner@gmail.com', true),
  ('273', 'Anna Furgał', NULL, 'delek10@interia.pl', true),
  ('274', 'Magdalena Zadencka', '663511543', 'magdalena.brodala@g4geodezja.pl', true),
  ('275', 'HallerDeHallenburg Monika', NULL, NULL, true),
  ('276', 'Łukasz Kozłowski', '515 540 144', 'lukasz.kozlowski88@o2.pl', true),
  ('280', 'Tomasz Nieradka', '531840567', 'tomnier99@gmail.com', true),
  ('281', 'Paulina Puszkarska', '791165812', 'paulina_puszkarska@vp.pl', true),
  ('282', 'Monika Orzeł', '730 914 821', 'monika.orzel@g4geodezja.pl', true),
  ('283', 'Kamil Łazarski', '661761258', 'lazarski.kontakt@gmail.com', true),
  ('284', 'Aleksandra Nieradka', NULL, 'ola931212@o2.pl', true),
  ('285', 'Patryk Pinda', '501 548 243', 'patrykpinda98@gmail.com', true),
  ('286', 'Paulina Domin', '666617930', 'paulina.domin@g4geodezja.pl', true),
  ('287', 'Kinga Dudek', '666335705', 'kinga.domin@g4geodezja.pl', true),
  ('288', 'Jakub Jamróz', '698194310', 'jakub.jamróz@g4geodezja.pl', true),
  ('289', 'Andrzej Płatek', NULL, NULL, true),
  ('290', 'Karolina Kluba', NULL, NULL, true),
  ('291', 'Krzysztof Jarzyna ze Szczecina', NULL, NULL, true)
;

INSERT INTO public.pracownik (nr, imie_nazwisko, telefon, email, is_active)
SELECT
  s.nr,
  s.imie_nazwisko,
  s.telefon,
  CASE
    WHEN NULLIF(trim(coalesce(s.email, '')), '') IS NULL THEN NULL
    WHEN EXISTS (
      SELECT 1
      FROM tmp_pracownik_import d
      WHERE d.nr <> s.nr
        AND lower(trim(coalesce(d.email, ''))) = lower(trim(coalesce(s.email, '')))
    ) THEN NULL
    WHEN EXISTS (
      SELECT 1
      FROM public.pracownik p
      WHERE p.nr <> s.nr
        AND lower(trim(coalesce(p.email, ''))) = lower(trim(coalesce(s.email, '')))
    ) THEN NULL
    ELSE s.email
  END AS email,
  s.is_active
FROM tmp_pracownik_import s
ON CONFLICT (nr) DO UPDATE SET
  imie_nazwisko = EXCLUDED.imie_nazwisko,
  telefon = EXCLUDED.telefon,
  email = EXCLUDED.email,
  is_active = EXCLUDED.is_active;

COMMIT;
