-- =============================================================================
-- Dokumenty HR dla pracownika (linki do plików: umowa, BHP, orzeczenie, kwitki)
-- + opcjonalny link do Google Sheet / Dysku w tabeli pracownik.
-- Uruchom w Supabase SQL Editor. Wymaga istniejącej tabeli public.pracownik.
-- =============================================================================

ALTER TABLE public.pracownik
  ADD COLUMN IF NOT EXISTS link_google_arkusz text;

COMMENT ON COLUMN public.pracownik.link_google_arkusz IS
  'Opcjonalny URL (np. wiersz w Google Sheet lub folder w Google Drive). Aplikacja nie synchronizuje Arkuszy — to tylko skrót.';

CREATE TABLE IF NOT EXISTS public.pracownik_dokument (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pracownik_nr text NOT NULL,
  typ text NOT NULL,
  url text NOT NULL,
  notatka text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT pracownik_dokument_typ_check CHECK (
    typ = ANY (
      ARRAY[
        'umowa',
        'bhp',
        'orzeczenie_lekarskie',
        'kwitek_wyplaty'
      ]::text[]
    )
  ),
  CONSTRAINT pracownik_dokument_nr_typ_unique UNIQUE (pracownik_nr, typ)
);

CREATE INDEX IF NOT EXISTS pracownik_dokument_prac_nr_idx
  ON public.pracownik_dokument (pracownik_nr);

COMMENT ON TABLE public.pracownik_dokument IS
  'Linki do dokumentów pracownika (URL — Google Drive, PDF, itp.). Jeden wpis na typ i numer ID.';

COMMENT ON COLUMN public.pracownik_dokument.typ IS
  'umowa | bhp | orzeczenie_lekarskie | kwitek_wyplaty';

ALTER TABLE public.pracownik_dokument ENABLE ROW LEVEL SECURITY;
